version: "3.8"
services:
  database:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nws
      MYSQL_USER: NWSocial
      MYSQL_PASSWORD: nws
      MYSQL_ALLOW_EMPTY_PASSWORD: valid
  phpmyadmin:
    links:
      - database
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: NWSocial
      PMA_PASSWORD: nws
    ports:
      - "8000:80"

volumes:
  db-data:
