version: "3.8"
services:
  api:
    depends_on:
      - database
    build: .
    ports:
      - "8081:80"
  database:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "8001:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'NWSocial'
      MYSQL_USER: 'NWSocial'
      MYSQL_PASSWORD: 'ekip'
      MYSQL_ROOT_PASSWORD: 'NRM LDO'

volumes:
  db-data:
